//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDeleter.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.12.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EmailAddress {
            get {
                return ((string)(this["EmailAddress"]));
            }
            set {
                this["EmailAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string IMAPServer {
            get {
                return ((string)(this["IMAPServer"]));
            }
            set {
                this["IMAPServer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseSSL {
            get {
                return ((bool)(this["UseSSL"]));
            }
            set {
                this["UseSSL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("993")]
        public int IMAPPort {
            get {
                return ((int)(this["IMAPPort"]));
            }
            set {
                this["IMAPPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Clear text authentication")]
        public string LogonUsing {
            get {
                return ((string)(this["LogonUsing"]));
            }
            set {
                this["LogonUsing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1753-01-01")]
        public global::System.DateTime FromDate {
            get {
                return ((global::System.DateTime)(this["FromDate"]));
            }
            set {
                this["FromDate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9998-12-31")]
        public global::System.DateTime ToDate {
            get {
                return ((global::System.DateTime)(this["ToDate"]));
            }
            set {
                this["ToDate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FromContains {
            get {
                return ((string)(this["FromContains"]));
            }
            set {
                this["FromContains"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ToContains {
            get {
                return ((string)(this["ToContains"]));
            }
            set {
                this["ToContains"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SubjectContains {
            get {
                return ((string)(this["SubjectContains"]));
            }
            set {
                this["SubjectContains"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BodyContains {
            get {
                return ((string)(this["BodyContains"]));
            }
            set {
                this["BodyContains"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Vf9HzUEBJPmZ7w2KiGJocUfgie7VlilgVfbSW5l9g1Q=")]
        public string AppString1 {
            get {
                return ((string)(this["AppString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("APFeALg3dJrzKJoxNP/O/hKo3vJ6kQjWG7Mnsf4Wbkz6F6f+NmWufl9EGCYnn8JH8YYxmAJRovNKeuWc5" +
            "IX7eg==")]
        public string AppString2 {
            get {
                return ((string)(this["AppString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ZInWBH3xESgI8Qga7z4swkyPxwAhMkl57Bkh1TCUPcYeRC9hrcuBD68xGQZDFp/31ZdQpYF0T3GaVXyya" +
            "SShG+eiBM0AiyVF900k1IP6d5kaZd0AdBz0unPFRNMC3+ij")]
        public string AppString3 {
            get {
                return ((string)(this["AppString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EGcFM094CYRZtJwA5xerVw9G50NN2vT69EfpKdBkiesIrHfhpWSgUE7faQ90hPOhWc0z4EP6QYZLn22wJ" +
            "Qs7FA==")]
        public string AppString4 {
            get {
                return ((string)(this["AppString4"]));
            }
        }
    }
}
